[book]
title = "codemelted.rs: The Swiss Army Knife Full Stack Solution"
authors = ["Mark Shaffer"]
description = "An implementation of 14 domain specific use cases to bring a full stack solution for CLI, services, and web development."
language = "en"
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "navy"
site-url = "https://rs.codemelted.com/mdbook"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
